######################################################################
# QT Project file
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . . Source
INCLUDEPATH += . Source

# Input
HEADERS += $$(SRC_DIR)/DT3LevelEditor/EdLevelAppMain.hpp $$(SRC_DIR)/DT3LevelEditor/EdLevelMainWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertiesWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyBase.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyDefaultField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyVector2Field.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyVector3Field.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyMatrix3Field.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyColorField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyTitleField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyBoolField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyEventField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyEnumField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyRangeField.hpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelColorSwatch.hpp $$(SRC_DIR)/DT3LevelEditor/Game/EdLevelGame.hpp $$(SRC_DIR)/DT3LevelEditor/Game/EdLevelGameGL.hpp $$(SRC_DIR)/DT3LevelEditor/Hierarchy/EdLevelHierarchyWindow.hpp  $$(SRC_DIR)/DT3LevelEditor/Hierarchy/EdLevelHierarchyWindowMIME.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptConnectionRubberBand.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptEventConnection.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptNodeStandard.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptPlugConnection.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptSelectionRubberBand.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptNodeStandard.hpp $$(SRC_DIR)/DT3LevelEditor/Console/EdLevelConsoleWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Performance/EdLevelPerformanceWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourcesWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Library/EdLevelLibraryWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Library/EdLevelLibraryDialog.hpp $$(SRC_DIR)/DT3LevelEditor/World/EdLevelWorldWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Animation/EdLevelAnimationWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Sound/EdLevelSoundWindow.hpp $$(SRC_DIR)/DT3LevelEditor/Sound/EdLevelSoundBus.hpp $$(SRC_DIR)/DT3LevelEditor/Sound/EdLevelSoundVUMeter.hpp $$(SRC_DIR)/DT3LevelEditor/EdLevelToolWindow.hpp  $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelImageThumbnail.hpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelSoundThumbnail.hpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelMaterialThumbnail.hpp  $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourceImage.hpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourceSound.hpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourceMaterial.hpp $$(SRC_DIR)/DT3LevelEditor/EdLevelLineEdit.hpp  $$(SRC_DIR)/DT3LevelEditor/EdLevelLaunchDialog.hpp $$(SRC_DIR)/DT3LevelEditor/MeshBuilder/EdLevelMeshBuilder.hpp
SOURCES += $$(SRC_DIR)/DT3LevelEditor/EdLevelAppMain.cpp $$(SRC_DIR)/DT3LevelEditor/EdLevelMainWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertiesWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyBase.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyDefaultField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyVector3Field.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyMatrix3Field.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyColorField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyTitleField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyBoolField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyEventField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyEnumField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelPropertyRangeField.cpp $$(SRC_DIR)/DT3LevelEditor/Properties/EdLevelColorSwatch.cpp $$(SRC_DIR)/DT3LevelEditor/Game/EdLevelGame.cpp $$(SRC_DIR)/DT3LevelEditor/Game/EdLevelGameGL.cpp $$(SRC_DIR)/DT3LevelEditor/Hierarchy/EdLevelHierarchyWindow.cpp  $$(SRC_DIR)/DT3LevelEditor/Hierarchy/EdLevelHierarchyWindowMIME.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptConnectionRubberBand.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptEventConnection.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptNodeStandard.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptPlugConnection.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptSelectionRubberBand.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Scripting/EdLevelScriptNodeStandard.cpp $$(SRC_DIR)/DT3LevelEditor/Console/EdLevelConsoleWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Performance/EdLevelPerformanceWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourcesWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Library/EdLevelLibraryWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Library/EdLevelLibraryDialog.cpp $$(SRC_DIR)/DT3LevelEditor/World/EdLevelWorldWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Animation/EdLevelAnimationWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Sound/EdLevelSoundWindow.cpp $$(SRC_DIR)/DT3LevelEditor/Sound/EdLevelSoundBus.cpp $$(SRC_DIR)/DT3LevelEditor/Sound/EdLevelSoundVUMeter.cpp $$(SRC_DIR)/DT3LevelEditor/EdLevelToolWindow.cpp  $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelImageThumbnail.cpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelSoundThumbnail.cpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelMaterialThumbnail.cpp  $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourceImage.cpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourceSound.cpp $$(SRC_DIR)/DT3LevelEditor/Resources/EdLevelResourceMaterial.cpp $$(SRC_DIR)/DT3LevelEditor/EdLevelLineEdit.cpp $$(SRC_DIR)/DT3LevelEditor/EdLevelLaunchDialog.cpp $$(SRC_DIR)/DT3LevelEditor/MeshBuilder/EdLevelMeshBuilder.cpp
RESOURCES += $$(SRC_DIR)/DT3LevelEditor/LevelEditor.qrc


